version: '3.4'
services:
  bsc.avado.dnp.dappnode.eth:
    image: 'bsc.avado.dnp.dappnode.eth:0.0.2'
    build:
      context: ./build
      args:
        - VERSION=1.1.0
    environment:
      - EXTRA_OPTS=
    volumes:
      - 'data:/package/data'
    ports:
      - '443:443'
      - '8545:8545'
      - '8546:8546'
      - '8547:8547'
      - '30303:30303/tcp'
      - '30303:30303/udp'
    logging:
      options:
        max-size: 10m
        max-file: '3'
volumes:
  data: {}
